app/snippets/blueprint.py
from flask import Blueprint, request, render_template, redirect, url_for
from helpers import object_list
from app import db, app
from models import Snippet
from forms import SnippetForm
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter

snippets = Blueprint('snippets', __name__, template_folder='templates')

@app.template_filter('pygments')
def pygments_filter(code):
    return highlight(code, PythonLexer(), HtmlFormatter())

@snippets.route('/')
def index():
    snippets = Snippet.query.order_by(Snippet.created_timestamp.desc())
    return object_list('entries/index.html', snippets)

@snippets.route('/<slug>/')
def detail(slug):
    snippet = Snippet.query.filter(Snippet .slug == slug).first_or_404()
    return render_template('snippets/detail.html', entry=snippet)

@snippets.route('/create/', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        form = SnippetForm(request.form)
        if form.validate():
            snippet = form.save_entry(Snippet())
            db.session.add(snippet)
            db.session.commit()
            return redirect(url_for('snippets.detail', slug=snippet.slug))
    else:
        form = SnippetForm()
    return render_template('snippets/create.html', form=form)

@snippets.route('/<slug>/edit/', methods=['GET', 'POST'])
def edit(slug):
    snippet = Snippet.query.filter(Snippet.slug == slug).first_or_404()
    if request.method == 'POST':
        form = SnippetForm(request.form, obj=snippet)
        if form.validate():
            snippet = form.save_entry(snippet)
            db.session.add(snippet)
            db.session.commit()
        return redirect(url_for('snippets.detail', slug=entry.slug))
    else:
        form = EntryForm(obj=entry)
        
    return render_template('entries/edit.html', entry=snippet, form=form)

app/snippets/templates/snippets/create.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{% block title %}Create new snippet{% endblock %}
{% block content_title %}Create new snippet{% endblock %}
{% block content %}
<form action="{{ url_for('snippets.create') }}" class="form form-horizontal" method="post">
{% for field in form %}
    {{ form_field(field) }}
{% endfor %}
<div class="form-group">
<div class="col-sm-offset-3 col-sm-9">
<button type="submit" class="btn btn-default">Create</button>
<a class="btn" href="{{ url_for('snippets.index')}}">Cancel</a>
</div>
</div>
</form>
{% endblock %}

app/snippets/templates/snippets/detail.html
{% extends "base.html" %}
{% block title %}{{ entry.title }} - Snippets{% endblock %}
{% block content_title %}Snippet{% endblock %}
{% block content %}
{{ entry.body | pygments | safe}}
{% endblock %}